#!/usr/bin/env node
// Exercise real app click handlers and the real pinyin player with browser media
// and HTTP doubles. Tests never connect to the learner's progress database.
"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const vm = require("node:vm");
const publicDir = path.join(__dirname, "../public");
const source = fs.readFileSync(path.join(publicDir, "app.js"), "utf8");
const instrumented = source.replace(/\}\)\(\);\s*$/, `
globalThis.subject = {
 navigate, openParent, openReviewItem, loadState,
 getView: () => currentView,
 getPracticed: () => Array.from(pyPracticed),
 getSelected: () => pySelected,
 getSession: () => reviewSession,
 setSession: value => { reviewSession = value; },
 prime: state => {
   acceptServerState({found:true,payload:state});
   POEMS = []; BUILTIN_POEMS = []; poemsLoadPromise = Promise.resolve([]);
 }
};
})();`);
assert.notEqual(instrumented, source, "App must be an IIFE for in-memory test exports");
const copy = value => JSON.parse(JSON.stringify(value));
const flush = () => new Promise(resolve => setImmediate(resolve));
const read = name => fs.readFileSync(path.join(publicDir, name), "utf8");

function harness(initial = {}) {
  const elements = new Map(), recordings = [], requests = [], timers = new Map();
  let timerId = 0, failNextSave = false, holdSaves = false;
  let database = { items: {}, activity: {}, customPoems: {}, customCharacters: {}, hiddenCourses: {}, ...copy(initial) };
  const datasetName = name => name.slice(5).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  const matches = (element, selector) => {
    if (/^[a-z]+$/.test(selector)) return element.tagName === selector;
    if (selector.startsWith("#")) return element.id === selector.slice(1);
    if (selector.startsWith(".")) return element.classList.contains(selector.slice(1));
    const attr = selector.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);
    return !!attr && element.attributes.has(attr[1]) && (attr[2] === undefined || element.attributes.get(attr[1]) === attr[2]);
  };
  function element(id = "") {
    const classes = new Set(), attributes = new Map();
    const node = {
      id, attributes, children: [], dataset: {}, style: {}, textContent: "", value: "", open: false, disabled: false, hidden: false,
      classList: {
        contains: name => classes.has(name), add: name => classes.add(name), remove: name => classes.delete(name),
        toggle(name, force) { const next = force === undefined ? !classes.has(name) : force; if (next) classes.add(name); else classes.delete(name); return next; },
      },
      setAttribute(name, value) {
        attributes.set(name, String(value));
        if (name === "id") { this.id = value; elements.set(value, this); }
        if (name === "class") String(value).split(/\s+/).filter(Boolean).forEach(name => classes.add(name));
        if (name.startsWith("data-")) this.dataset[datasetName(name)] = value;
        if (name === "disabled") this.disabled = true;
        if (name === "hidden") this.hidden = true;
        if (name === "value") this.value = value;
      },
      getAttribute: name => attributes.get(name) ?? null,
      removeAttribute: name => attributes.delete(name),
      querySelectorAll(selector) { return this.children.filter(child => matches(child, selector)); },
      querySelector(selector) { return this.querySelectorAll(selector)[0] || null; },
      addEventListener() {}, scrollIntoView() {}, focus() {}, setSelectionRange() {}, reset() {},
      showModal() { this.open = true; }, close() { this.open = false; },
    };
    Object.defineProperty(node, "innerHTML", {
      get() { return this.html || ""; },
      set(html) {
        for (const child of this.children) if (child.id && elements.get(child.id) === child) elements.delete(child.id);
        this.html = html; this.children = [];
        // Only DOM attributes/selectors are modeled; content and handlers are
        // always generated by app.js, including a fresh button on each render.
        for (const tag of html.matchAll(/<([a-z][a-z0-9-]*)\b([^>]*)>/gi)) {
          const child = element();
          child.tagName = tag[1].toLowerCase();
          for (const attr of tag[2].matchAll(/([\w-]+)(?:="([^"]*)")?/g)) child.setAttribute(attr[1], attr[2] ?? "");
          this.children.push(child);
        }
      },
    });
    if (id) elements.set(id, node);
    return node;
  }
  const views = ["home", "poems", "poem-detail", "math", "pinyin", "write", "write-detail", "english", "records"];
  for (const id of [...views.map(view => `${view}-content`), "parent-dialog", "sync-status", "live-status", "toast"]) element(id);
  for (const view of views) {
    elements.get(`${view}-content`).dataset.view = view;
    elements.get(`${view}-content`).classList.add("view");
  }
  class Audio {
    constructor() { this.events = new Map(); this.attempts = []; this.paused = true; this.currentTime = 0; this.pauseCalls = 0; recordings.push(this); }
    addEventListener(name, handler) { if (!this.events.has(name)) this.events.set(name, new Set()); this.events.get(name).add(handler); }
    removeEventListener(name, handler) { this.events.get(name)?.delete(handler); }
    play() {
      this.paused = false;
      const attempt = { src: this.src };
      const promise = new Promise((resolve, reject) => { attempt.resolve = resolve; attempt.reject = reject; });
      this.attempts.push(attempt);
      return promise;
    }
    pause() { this.paused = true; this.pauseCalls++; }
    load() { this.currentTime = 0; }
    removeAttribute(name) { delete this[name]; }
    emit(name) { this[`on${name}`]?.(); for (const handler of [...(this.events.get(name) || [])]) handler(); }
  }
  const window = { Audio, scrollY: 0, scrollTo() {}, addEventListener() {}, confirm: () => true };
  const context = vm.createContext({
    window, console, Date, Math, AbortController,
    document: {
      getElementById: id => elements.get(id) || null,
      querySelectorAll: selector => selector === ".view" ? views.map(view => elements.get(`${view}-content`)) : [],
      querySelector: selector => selector.startsWith("#") ? elements.get(selector.slice(1)) || null : null,
      addEventListener() {}, createElement: () => element(), body: { appendChild(node) { elements.set(node.id, node); } },
    },
    setTimeout: (fn, delay) => { const id = ++timerId; timers.set(id, { fn, delay }); return id; },
    clearTimeout: id => timers.delete(id),
    fetch: async (url, options = {}) => {
      assert.equal(url, "/api/progress", "Tests must not fetch remote resources or actual audio");
      const request = { url, method: options.method || "GET", body: options.body ? JSON.parse(options.body) : null };
      requests.push(request);
      if(holdSaves&&request.method==="PATCH") {
        try {await new Promise((resolve,reject)=>{request.release=resolve;request.fail=()=>reject(new Error("Offline"));});}
        finally {request.settled=true;}
      }
      if (failNextSave) { failNextSave = false; throw new Error("Offline"); }
      if (request.method === "PATCH") {
        for (const op of request.body.operations) {
          if (op.op === "set") database[op.collection][op.key] = copy(op.value);
          else if (op.op === "create") { if (!Object.hasOwn(database[op.collection],op.key)) database[op.collection][op.key] = copy(op.value); }
          else if (op.op === "merge") Object.assign(database[op.collection][op.key], copy(op.value));
          else assert.fail(`Unexpected save operation: ${op.op}`);
        }
      }
      return { ok: true, status: 200, json: async () => ({ ok: true, found: true, payload: copy(database) }) };
    },
  });
  for (const script of ["writing-vocabulary.js", "pinyin-data.js", "pinyin-audio.js", "learning-model.js"]) vm.runInContext(read(script), context);
  vm.runInContext(instrumented, context, { filename: "app.js" });
  context.subject.prime(copy(database));
  context.subject.navigate("pinyin");
  const get = id => { const node = elements.get(id); assert.ok(node, `Rendered element #${id} must exist`); return node; };
  const select = selector => { const node = get("pinyin-content").querySelector(selector); assert.ok(node, `Rendered control ${selector} must exist`); return node; };
  const click = node => { assert.equal(typeof node.onclick, "function", "Control must have an app handler"); return node.onclick({ currentTarget: node }); };
  return { subject: context.subject, window, get, select, click, recordings, requests, data: copy(window.ChenchenPinyinData),
    db: () => copy(database), failSave: () => { failNextSave = true; },
    holdSaves: value => {holdSaves=value;},
    async nextSave() {await flush();const request=requests.find(request=>request.release&&!request.settled);assert.ok(request,"Expected a held save");return request;},
    audio: () => recordings.at(-1), allAttempts: () => recordings.flatMap(recording => recording.attempts),
  };
}

test("opening pinyin is silent and the large pinyin button starts only its sound synchronously", async () => {
  const h = harness();
  assert.equal(h.recordings.length, 0);
  assert.equal(h.subject.getSelected(), "b");
  assert.equal(h.get("pinyin-content").querySelector("#py-finish"), null);
  const button = h.get("py-listen"), result = h.click(button);
  assert.equal(h.audio().attempts[0].src, "/audio/pinyin/sound-b.mp3");
  assert.equal(button.classList.contains("is-reading"), true);
  assert.equal(button.getAttribute("aria-busy"), "true");
  h.audio().emit("ended"); await result;
  assert.equal(button.classList.contains("is-reading"), false);
  assert.equal(button.getAttribute("aria-busy"), null);
  assert.equal(h.requests.length, 0);
});

test("all 47 cards play their exact sound and render three independently spoken example characters", async () => {
  const h = harness();
  for (const tab of ["initials", "finals"]) {
    h.click(h.select(`[data-pt="${tab}"]`));
    for (const item of h.data[tab]) {
      h.click(h.select(`[data-p="${item.id}"]`));
      assert.equal(h.audio().attempts.at(-1).src, `/audio/pinyin/sound-${item.id.replace(/ü/g, "v")}.mp3`);
      assert.equal(h.get("py-listen").getAttribute("aria-label"), `听拼音 ${item.id}`);
      assert.equal(h.get("pinyin-content").querySelectorAll("[data-py-example]").length, 3);
      h.audio().emit("ended"); await flush();
      for (const example of item.examples) {
        assert.ok(h.get("pinyin-content").innerHTML.includes(`<ruby>${example.c}<rt>${example.pinyin}</rt></ruby>`));
        const result = h.click(h.select(`[data-py-example="${example.c}"]`));
        assert.equal(h.audio().attempts.at(-1).src, `/audio/pinyin/examples/char-${example.c.codePointAt(0).toString(16)}.mp3`);
        h.audio().emit("ended"); await result;
      }
    }
  }
  assert.equal(h.allAttempts().length, 47 * 4);
  assert.equal(h.recordings.length, 1, "Renders and tab changes must preserve the unlocked Audio element");
  assert.deepEqual(copy(h.subject.getPracticed()), []);
  assert.equal(h.requests.length, 0, "Listening alone must not save or complete practice");
});

test("changing the sound or tab stops old narration and cannot display its late error", async () => {
  const h = harness();
  const firstButton = h.get("py-listen"), first = h.click(firstButton), audio = h.audio();
  const oldAttempt = audio.attempts[0];
  h.click(h.select('[data-p="m"]'));
  await first;
  const currentButton = h.get("py-listen");
  assert.equal(currentButton.classList.contains("is-reading"), true);
  assert.equal(firstButton.classList.contains("is-reading"), false);
  assert.equal(audio.attempts.at(-1).src, "/audio/pinyin/sound-m.mp3");
  oldAttempt.reject(new Error("Old audio failed")); await flush();
  assert.equal(h.get("py-audio-status").textContent, "");
  assert.equal(currentButton.classList.contains("is-reading"), true);
  h.click(h.select('[data-pt="finals"]')); await flush();
  assert.equal(audio.paused, true);
  assert.equal(currentButton.classList.contains("is-reading"), false);
  assert.equal(h.subject.getSelected(), "a");
  assert.equal(audio.attempts.length, 2, "Changing tabs must not autoplay");
  assert.equal(h.requests.length, 0);
});

test("rapid example clicks clear old highlights but preserve the current request", async () => {
  const h = harness();
  const firstButton = h.select('[data-py-example="爸"]'), first = h.click(firstButton);
  const firstAttempt = h.audio().attempts[0];
  const nextButton = h.select('[data-py-example="包"]'), next = h.click(nextButton);
  await first;
  assert.equal(firstButton.classList.contains("is-reading"), false);
  assert.equal(nextButton.classList.contains("is-reading"), true);
  firstAttempt.reject(new Error("Late example failure")); await flush();
  assert.equal(h.get("py-audio-status").textContent, "");
  assert.equal(nextButton.classList.contains("is-reading"), true);
  h.audio().emit("ended"); await next;
  assert.equal(nextButton.classList.contains("is-reading"), false);
  assert.equal(h.requests.length, 0);
});

test("the UI itself ignores late failures even if an audio adapter cannot cancel promptly", async () => {
  const h = harness(), pending = [];
  const play = () => new Promise((resolve, reject) => pending.push({ resolve, reject }));
  h.window.ChenchenPinyinAudio = { create: () => ({ playSound: play, playExample: play, stop() {}, destroy() {} }) };
  const firstButton = h.get("py-listen"), first = h.click(firstButton);
  h.click(h.select('[data-p="m"]'));
  const currentButton = h.get("py-listen");
  pending[0].reject(new Error("Uncancelled old failure")); await first;
  assert.equal(h.get("py-audio-status").textContent, "");
  assert.equal(currentButton.classList.contains("is-reading"), true);
  assert.equal(firstButton.classList.contains("is-reading"), false);
  h.subject.navigate("write");
  pending[1].reject(new Error("Failure after leaving")); await flush();
  assert.equal(h.subject.getView(), "write");
  assert.equal(h.get("py-audio-status").textContent, "");
  assert.equal(currentButton.classList.contains("is-reading"), false);
  assert.equal(h.requests.length, 0);
});

test("leaving the page destroys narration and a late event cannot restart it", async () => {
  const h = harness(), button = h.get("py-listen"), result = h.click(button), audio = h.audio();
  h.subject.navigate("write"); await result;
  assert.equal(h.subject.getView(), "write");
  assert.equal(audio.paused, true);
  assert.equal(audio.src, undefined);
  assert.equal(button.classList.contains("is-reading"), false);
  audio.emit("playing"); audio.attempts[0].reject(new Error("Late failure")); await flush();
  assert.equal(audio.paused, true);
  assert.equal(h.get("py-audio-status").textContent, "");
  h.subject.navigate("pinyin");
  const next = h.click(h.get("py-listen"));
  assert.equal(h.recordings.length, 2, "Returning creates a fresh lifetime after destroy");
  h.audio().emit("ended"); await next;
  assert.equal(h.requests.length, 0);
});

test("opening the parent dialog cancels narration without completing or replacing the card", async () => {
  const h = harness(), result = h.click(h.get("py-listen")), audio = h.audio();
  await h.subject.openParent(); await result;
  assert.equal(h.get("parent-dialog").open, true);
  assert.equal(h.subject.getView(), "pinyin");
  assert.equal(h.subject.getSelected(), "b");
  assert.equal(audio.paused, true);
  assert.equal(h.get("py-listen").classList.contains("is-reading"), false);
  audio.attempts[0].reject(new Error("Late failure")); await flush();
  assert.equal(h.get("py-audio-status").textContent, "");
  assert.equal(h.requests.length, 0);
});

test("failed playback shows a concise retry and a second tap clears the error", async () => {
  const h = harness(), button = h.get("py-listen"), result = h.click(button);
  h.audio().emit("error"); await result;
  assert.equal(h.get("py-audio-status").textContent, "声音没播放，再点一下。");
  assert.equal(button.classList.contains("is-reading"), false);
  assert.equal(button.disabled, false);
  const retry = h.click(button);
  assert.equal(h.get("py-audio-status").textContent, "");
  assert.equal(h.audio().attempts.length, 2);
  h.audio().emit("ended"); await retry;
  assert.equal(h.requests.length, 0);
});

test("a missing audio module offers the same retry and can recover without rerender", async () => {
  const h = harness(), module = h.window.ChenchenPinyinAudio;
  h.window.ChenchenPinyinAudio = undefined;
  await h.click(h.get("py-listen"));
  assert.equal(h.get("py-audio-status").textContent, "声音没播放，再点一下。");
  assert.equal(h.recordings.length, 0);
  h.window.ChenchenPinyinAudio = module;
  const retry = h.click(h.get("py-listen"));
  h.audio().emit("ended"); await retry;
  assert.equal(h.get("py-audio-status").textContent, "");
});

test("each parent confirmation saves that sound immediately and survives leaving after one card", async () => {
  const h = harness();
  assert.equal(h.get("pinyin-content").querySelector("#py-finish"), null);
  assert.ok(h.get("pinyin-content").innerHTML.includes('id="py-read">确认练习</button>'));
  const playback = h.click(h.get("py-listen"));
  h.click(h.get("py-read")); await playback;
  assert.equal(h.audio().paused, true);
  assert.equal(h.get("py-assessment").hidden, false);
  assert.deepEqual(copy(h.subject.getPracticed()), []);
  assert.equal(h.requests.length, 0, "Opening confirmation must not record a result");
  await h.click(h.get("py-check-supported"));
  assert.deepEqual(copy(h.subject.getPracticed()), ["b"]);
  assert.equal(h.subject.getSelected(), "p");
  assert.equal(h.requests.length, 1, "Confirmation itself persists the completed sound");
  assert.equal(h.requests[0].method, "PATCH");
  assert.equal(h.subject.getView(), "pinyin");
  const activity = Object.values(h.db().activity);
  assert.equal(activity.length, 1);
  assert.equal(activity[0].id, "pinyin-b");
  assert.equal(activity[0].result, "supported");
  assert.equal(activity[0].source, "parent"); assert.equal(activity[0].skill, "pinyin-reading");
  assert.equal(activity[0].details.afterPractice, true);
  assert.deepEqual(Object.keys(h.db().items), ["pinyin-b"], "Only confirmed sounds join review");
  h.subject.navigate("write");
  assert.equal(Object.values(h.db().activity).length, 1, "Leaving after one card must not discard a confirmed result");
});

test("three distinct confirmed sounds finish free practice without a separate completion button", async () => {
  const h = harness();
  for (const [symbol, result] of [["b", "independent"], ["p", "supported"], ["m", "again"]]) {
    assert.equal(h.subject.getSelected(), symbol);
    assert.equal(h.get("pinyin-content").querySelector("#py-finish"), null);
    h.click(h.get("py-read"));
    await h.click(h.get(`py-check-${result}`));
  }
  assert.equal(h.subject.getView(), "home");
  assert.deepEqual(Object.values(h.db().activity).map(event => [event.id, event.result]), [
    ["pinyin-b", "independent"], ["pinyin-p", "supported"], ["pinyin-m", "again"],
  ]);
  assert.equal(h.requests.length, 3);
});

test("failed immediate confirmation stays on the sound and retries its original activity without duplication", async () => {
  const h = harness(); h.click(h.get("py-read")); h.failSave();
  await h.click(h.get("py-check-independent"));
  assert.equal(h.subject.getView(), "pinyin");
  assert.equal(h.subject.getSelected(), "b");
  assert.deepEqual(copy(h.subject.getPracticed()), [], "A failed save cannot look completed");
  assert.equal(Object.keys(h.db().activity).length, 0);
  assert.ok(h.get("pinyin-content").querySelectorAll("button").filter(button => button.id !== "py-check-independent").every(button => button.disabled), "A failed confirmation freezes every control except its original retry");
  assert.equal(h.get("py-check-independent").disabled, false);
  assert.match(h.get("py-check-independent").textContent, /重试保存/);
  await h.click(h.get("py-check-independent")); await flush();
  assert.equal(h.subject.getView(), "pinyin");
  assert.equal(h.subject.getSelected(), "p");
  assert.deepEqual(copy(h.subject.getPracticed()), ["b"]);
  assert.equal(Object.keys(h.db().activity).length, 1);
  assert.deepEqual(h.requests[0].body.operations, h.requests[1].body.operations);
});

test("a legacy scheduled pinyin group saves one actual sound, retires the group and advances once", async () => {
  const item = { id: "pinyin-basic", title: "声母韵母认读", type: "pinyin", learned: true, stage: 0, nextReview: "2020-01-01" };
  const h = harness({ items: { [item.id]: item } });
  h.subject.setSession({ items: [item], index: 0 }); h.subject.openReviewItem(item.id, item.type);
  const sound = h.click(h.get("py-listen"));
  h.click(h.get("py-read")); await sound;
  await h.click(h.get("py-check-independent"));
  assert.equal(h.subject.getSession(), null);
  assert.equal(h.subject.getView(), "home");
  assert.equal(h.audio().paused, true);
  assert.equal(h.db().items[item.id].learned, false);
  assert.equal(h.db().items["pinyin-b"].learned, true);
  assert.equal(h.db().items["pinyin-b"].stage, 0, "A just-rehearsed sound must not lengthen its interval");
  assert.equal(Object.keys(h.db().activity).length, 1);
  assert.equal(Object.values(h.db().activity)[0].id, "pinyin-b");
  assert.equal(h.requests.length, 1);
});

test("an individual umlaut sound opens a silent recall check and saves under its stable v spelling", async () => {
  for (const [id, symbol] of [["pinyin-v", "ü"], ["pinyin-vn", "ün"]]) {
    const item = { id, title: `拼音·${symbol}`, type: "pinyin", learned: true, stage: 2, nextReview: "2020-01-01" };
    const h = harness({ items: { [id]: item } });
    h.subject.setSession({ items: [item], index: 0 }); h.subject.openReviewItem(id, "pinyin");
    assert.equal(h.subject.getSelected(), symbol); assert.equal(h.get("py-assessment").hidden, false);
    assert.equal(h.allAttempts().length, 0, "Review must let the child recall before hearing a model");
    assert.equal(h.get("pinyin-content").querySelector("#py-finish"), null);
    await h.click(h.get("py-check-independent"));
    const event = Object.values(h.db().activity)[0];
    assert.equal(event.id, id); assert.equal(event.result, "independent"); assert.equal(event.details.symbol, symbol);
    assert.equal(event.details.afterPractice, false); assert.equal(h.db().items[id].stage, 3);
    assert.equal(h.subject.getSession(), null);
  }
});

test("a hint during scheduled recall is recorded and does not increase the memorized interval", async () => {
  const item = { id: "pinyin-b", title: "拼音·b", type: "pinyin", learned: true, stage: 2, nextReview: "2020-01-01" };
  const h = harness({ items: { [item.id]: item } });
  h.subject.setSession({ items: [item], index: 0 }); h.subject.openReviewItem(item.id, "pinyin");
  const sound = h.click(h.get("py-check-hint")); h.audio().emit("ended"); await sound;
  await h.click(h.get("py-check-independent"));
  const event = Object.values(h.db().activity)[0];
  assert.equal(event.result, "independent"); assert.equal(event.details.afterPractice, true);
  assert.equal(h.db().items[item.id].stage, 0, "Hearing the model must schedule another near-term check");
});

test("a scheduled sound stays on its target even after returning to practice", async () => {
  const item = { id: "pinyin-b", title: "拼音·b", type: "pinyin", learned: true, stage: 2, nextReview: "2020-01-01" };
  const h = harness({ items: { [item.id]: item } });
  h.subject.setSession({ items: [item], index: 0 }); h.subject.openReviewItem(item.id, "pinyin");
  assert.equal(h.select(".pinyin-grid").hidden, true, "Scheduled recall must not expose a switch to an unrelated sound");
  assert.equal(h.select(".tabs-mini").hidden, true);
  h.click(h.select('[data-p="m"]')); h.click(h.select('[data-pt="finals"]'));
  assert.equal(h.subject.getSelected(), "b", "Even stale card handlers cannot replace the scheduled target");
  h.click(h.get("py-check-back"));
  assert.equal(h.get("py-assessment").hidden, true);
  assert.equal(h.select(".pinyin-grid").hidden, true);
  assert.equal(h.select(".tabs-mini").hidden, true);
  const sound = h.click(h.get("py-listen")); h.audio().emit("ended"); await sound;
  h.click(h.get("py-read")); await h.click(h.get("py-check-independent"));
  const events = Object.values(h.db().activity);
  assert.equal(events.length, 1); assert.equal(events[0].id, item.id); assert.equal(events[0].details.afterPractice, true);
  assert.equal(h.subject.getSession(), null);
});

test("repeated confirmations retain their evidence while abandoning an unconfirmed card records nothing", async () => {
  const h = harness();
  h.click(h.get("py-read")); await h.click(h.get("py-check-again"));
  h.click(h.select('[data-p="b"]')); h.click(h.get("py-read")); await h.click(h.get("py-check-independent"));
  const events = Object.values(h.db().activity);
  assert.deepEqual(events.map(event => event.result), ["again", "independent"]);
  assert.ok(events.every(event => event.id === "pinyin-b"));
  assert.deepEqual(copy(h.subject.getPracticed()), ["b"], "Repeating one sound must not count as three different cards");
  const other = harness(); other.click(other.get("py-read")); other.subject.navigate("write");
  assert.equal(other.requests.length, 0); assert.deepEqual(other.db().activity, {});
});

test("leaving failed pinyin practice permits a new result for the same sound on a fresh page", async () => {
  const h = harness(); h.click(h.get("py-read")); h.failSave();
  await h.click(h.get("py-check-independent"));
  const oldEvent = h.requests[0].body.operations.find(op => op.collection === "activity");
  h.subject.navigate("write"); h.subject.navigate("pinyin"); h.click(h.select('[data-p="b"]'));
  assert.equal(h.get("py-check-again").disabled, false);
  h.click(h.get("py-read")); await h.click(h.get("py-check-again"));
  const newEvent = h.requests[1].body.operations.find(op => op.collection === "activity");
  assert.notEqual(newEvent.key, oldEvent.key); assert.equal(newEvent.value.id, "pinyin-b"); assert.equal(newEvent.value.result, "again");
  assert.equal(Object.values(h.db().activity).length, 1);
});

test("an old pinyin save cannot navigate away from or unlock another round saving the same sound", async () => {
  const h = harness(); h.click(h.get("py-read")); h.holdSaves(true);
  const firstSave = h.click(h.get("py-check-independent")), first = await h.nextSave();
  assert.equal(h.get("py-check-independent").disabled, true);
  assert.equal(h.get("py-check-back").disabled, true);
  assert.deepEqual(copy(h.subject.getPracticed()), [], "An in-flight save has not completed the card");
  h.subject.navigate("write"); h.subject.navigate("pinyin"); h.click(h.select('[data-p="b"]'));
  h.click(h.get("py-read"));
  const newSave = h.click(h.get("py-check-supported")), newChoice = h.get("py-check-supported");
  assert.equal(newChoice.disabled, true);
  first.release(); await firstSave;
  const second = await h.nextSave();
  assert.equal(h.subject.getView(), "pinyin"); assert.equal(h.get("py-check-supported"), newChoice);
  assert.equal(h.subject.getSelected(), "b");
  assert.equal(newChoice.disabled, true, "The old callback must not unlock a new in-flight choice");
  assert.equal(h.get("py-check-again").disabled, true);
  second.release(); await newSave;
  assert.equal(h.subject.getView(), "pinyin"); assert.equal(h.subject.getSelected(), "p");
  assert.deepEqual(Object.values(h.db().activity).map(event => event.result), ["independent", "supported"]);
});

test("an old pinyin failure cannot freeze a newly reopened practice page", async () => {
  const h = harness(); h.click(h.get("py-read")); h.holdSaves(true);
  const save = h.click(h.get("py-check-independent")), first = await h.nextSave();
  h.subject.navigate("write"); h.subject.navigate("pinyin");
  const current = h.get("pinyin-content").innerHTML;
  first.fail(); await save;
  assert.equal(h.subject.getView(), "pinyin"); assert.equal(h.get("pinyin-content").innerHTML, current);
  assert.equal(h.get("py-listen").disabled, false); assert.equal(h.get("py-check-independent").disabled, false);
  assert.equal(Object.values(h.db().activity).length, 0);
});
